### ISSUE TITLE
Use native prometheus aggregations instead of stats package

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/go-commons#30]
Looking at https://github.com/cloud-bulldozer/go-commons/blob/main/prometheus/prometheus.go#L89 which is used for the kube-burner ocp wrapper reporting mode, it looks like we are extracting all the datapoints over the timeseries and then feeding them into methods in stats package as per the aggregation required. It looks like prometheus supports aggregations natively (https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time) and we should switch over to using those for better consistency and confidence in our aggregations.

**Comment by smalleni** [comment]
@vishnuchalla @rsevilla87 @krishvoor FYI

**Comment by rsevilla87** [comment]
mm, this is interesting, I've digged a little in the avg_over_time() functions and I think we may use them by combining instant queries and using a time range with a colon notation in order to get the aggregated values up to the passed timestamp:

Example:

```shell
$ curl -s 'http://demo.robustperception.io:9090/api/v1/query?query=avg_over_time%28rate%28node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B2m%5D%29%5B10m%3A%5D%29&time=1691492504'    | jq .
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "cpu": "0",
          "env": "demo",
          "instance": "demo.do.prometheus.io:9100",
          "job": "node",
          "mode": "idle"
        },
        "value": [
          1691492504,
          "0.8361428571421476"
        ]
      }
    ]
  }
}
``` 

The above urlencoded query is actually `avg_over_time(rate(node_cpu_seconds_total{mode="idle"}[2m])[10m:])`

**Comment by rsevilla87** [comment]
I still have to verify whether this value is valid or not

**Comment by rsevilla87** [comment]
More tests:

Query: urlencode  'max_over_time(rate(node_forks_total[2m])[5h:])'
```shell
$ curl -s 'http://demo.robustperception.io:9090/api/v1/query?query=max_over_time%28rate%28node_forks_total%5B2m%5D%29%5B5h%3A%5D%29&time=1691492544'    | jq .
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "env": "demo",
          "instance": "demo.do.prometheus.io:9100",
          "job": "node"
        },
        "value": [
          1691492544,
          "2.400068573387811"
        ]
      }
    ]
  }
}
```


![image](https://github.com/cloud-bulldozer/go-commons/assets/4614641/1e0f21ce-0aee-4271-8033-5bed30fe6482)



Both values match

**Comment by vishnuchalla** [comment]
Yes we can fetch the aggregations over time and also within in a given time range
```
curl -kH "Authorization: Bearer TOKEN" 'PROM_URL/api/v1/query?query=avg_over_time(sum(irate(node_cpu_seconds_total[2h]))[2h:1h])'
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1691553906.635,"103.71599999999302"]}]}}
```
But the only thing missing from the existing [function](https://github.com/cloud-bulldozer/go-commons/blob/main/prometheus/prometheus.go#L89) is the `step` (sample collection interval), which I don't think we need here while calculating aggregations. Correct me If I am wrong!

**Comment by rsevilla87** [comment]
With the two previous PRs I think we can close this one
